export const TEST_ACTION_TYPE = 'TEST_ACTION_TYPE';

export const MESH_CHANGED = 'MESH_CHANGED';
export const MESH_SELECTED = 'MESH_SELECTED';
export const MESH_ATTACHED = 'MESH_ATTACHED';
export const MESH_DETACHED = 'MESH_DETACHED';

export const SCENE_CONTROLS_CHANGED = 'SCENE_CONTROLS_CHANGED';
export const SCENE_SNAP_CHANGED = 'SCENE_SNAP_CHANGED';
export const SCENE_SNAP_ENABLED = 'SCENE_SNAP_ENABLED';

export const SCENE_FOG_ENABLED = 'SCENE_FOG_ENABLED';
export const SCENE_FOG_COLOR_CHANGED = 'SCENE_FOG_COLOR_CHANGED';
export const SCENE_FOG_DENSITY_CHANGED = 'SCENE_FOG_DENSITY_CHANGED';

export const SCENE_SHADOWS_CHANGED = 'SCENE_SHADOWS_CHANGED';

export const NEW_PROJECT_COMPLETED = 'NEW_PROJECT_COMPLETED';
export const NEW_PROJECT_SAVING = 'NEW_PROJECT_SAVING';
export const NEW_PROJECT_SAVED = 'NEW_PROJECT_SAVED';
export const NEW_PROJECT_ERROR = 'NEW_PROJECT_ERROR';

export const SCENE_SAVE_REQUEST = 'SCENE_SAVE_REQUEST';
export const SCENE_SAVE_LOADING = 'SCENE_SAVE_LOADING';
export const SCENE_SAVE_SUCCESS = 'SCENE_SAVE_SUCCESS';
export const SCENE_SAVE_FAILURE = 'SCENE_SAVE_FAILURE';
