export const TEST_ACTION_TYPE = 'TEST_ACTION_TYPE';

export const MESH_CHANGED = 'MESH_CHANGED';
export const MESH_SELECTED = 'MESH_SELECTED';

export const SCENE_CONTROLS_CHANGED = 'SCENE_CONTROLS_CHANGED';

export const SCENE_FOG_ENABLED = 'SCENE_FOG_ENABLED';
export const SCENE_FOG_COLOR_CHANGED = 'SCENE_FOG_COLOR_CHANGED';
export const SCENE_FOG_DENSITY_CHANGED = 'SCENE_FOG_DENSITY_CHANGED';

export const SCENE_SHADOWS_CHANGED = 'SCENE_SHADOWS_CHANGED';
