import { Router } from 'mage-engine';

//<ASSETS_AUTOGENERATED>
const assets = {
    Audio : {},

    Video : {},

    Images : {},

    Textures: {},

    Models : {},

    General : {}
};
//</ASSETS_AUTOGENERATED>

//<CONFIG_AUTOGENERATED>
const config = {

    screen: {
        h : window ? window.innerHeight : 800,
        w : window ? window.innerWidth : 600,
        ratio : window ? (window.innerWidth/window.innerHeight) : (600/800),
        frameRate : 60,
        alpha: true
    },

    lights: {
        shadows: true
    },

    physics: {
        enabled: false
    },

    tween: {
        enabled: false
    },

    camera : {
        fov : 75,
        near : 0.1,
        far : 3000000
    }
};
//</CONFIG_AUTOGENERATED>

//<ROUTER_AUTOGENERATED>
//</ROUTER_AUTOGENERATED>
