export const SELECTION_CHANGE = "SELECTION_CHANGE";

export const SCENE_CONTROLS_CHANGED = "SCENE_CONTROLS_CHANGED";
export const SCENE_CONTROLS_SPACE_CHANGED = "SCENE_CONTROLS_SPACE_CHANGED";
export const SCENE_SNAP_CHANGED = "SCENE_SNAP_CHANGED";
export const SCENE_SNAP_ENABLED = "SCENE_SNAP_ENABLED";

export const HIERARCHY_CHANGE = "HIERARCHY_CHANGE";
